### ISSUE TITLE
Selected icon unknown in typeahead

### ISSUE THREAD

**Issue by Akryum** [vuejs/vue-issue#9]
Using Windows 7 (64 bits)
Latest Chrome or Firefox

![image](https://cloud.githubusercontent.com/assets/2798204/24044823/2d156c22-0b1d-11e7-8ce8-7d87eb879c77.png)

**Comment by znck** [comment]
😑  FontAwesome dep. I'll use unicode check (✓) instead.

**Comment by Akryum** [comment]
Isn't font-awesome included in the app?

**Comment by znck** [comment]
No.
